# Generated by Django 5.0.1 on 2024-01-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=10000)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
