# Generated by Django 5.0.1 on 2024-01-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
